# Generated by Django 5.1.2 on 2024-11-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxs', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_name', models.CharField(max_length=30, unique=True)),
                ('structure_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Repertoires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repertoire_name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oxs.user')),
            ],
        ),
        migrations.CreateModel(
            name='RepertoriVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=30)),
                ('moves', models.CharField(max_length=300)),
                ('repertoires', models.ManyToManyField(to='oxs.repertoires')),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.CharField(max_length=300)),
                ('structures', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oxs.structures')),
            ],
        ),
    ]
