# Generated by Django 5.1.2 on 2024-11-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxs', '0005_rename_repertorivariants_repertoirevariants'),
    ]

    operations = [
        migrations.AddField(
            model_name='repertoires',
            name='repertoire_color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black')], default='White', max_length=10),
        ),
        migrations.AddField(
            model_name='variants',
            name='variants_color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black')], default='White', max_length=10),
        ),
    ]
