# Generated by Django 5.1.2 on 2024-11-06 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxs', '0006_repertoires_repertoire_color_variants_variants_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='structures',
            name='structure_map',
            field=models.CharField(default='O', max_length=300),
        ),
        migrations.AlterField(
            model_name='variants',
            name='structures',
            field=models.ForeignKey(default='PDA_1', on_delete=django.db.models.deletion.CASCADE, to='oxs.structures', to_field='structure_name'),
        ),
    ]
