# Generated by Django 4.2.17 on 2024-12-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oxs', '0008_remove_structures_structure_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertoires',
            name='user',
            field=models.ForeignKey(default='John Doe', on_delete=django.db.models.deletion.CASCADE, to='oxs.user', to_field='name'),
        ),
    ]
