# Generated by Django 4.2.17 on 2025-01-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oxs', '0009_alter_repertoires_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repertoires',
            unique_together={('repertoire_name', 'user')},
        ),
    ]
