# Generated by Django 4.2.17 on 2025-01-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxs', '0010_alter_repertoires_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repertoirevariants',
            name='repertoires',
        ),
        migrations.AddField(
            model_name='repertoirevariants',
            name='repertoire_name',
            field=models.CharField(default='One', max_length=30),
        ),
        migrations.AddField(
            model_name='repertoirevariants',
            name='user',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
