# Generated by Django 4.2.17 on 2025-01-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oxs', '0011_remove_repertoirevariants_repertoires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertoirevariants',
            name='repertoire_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='repertoirevariants',
            name='user',
            field=models.ForeignKey(default='John Doe', on_delete=django.db.models.deletion.CASCADE, to='oxs.user', to_field='name'),
        ),
    ]
