# Generated by Django 4.2.17 on 2025-01-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oxs', '0012_alter_repertoirevariants_repertoire_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repertoirevariants',
            unique_together={('moves', 'repertoire_name', 'user')},
        ),
    ]
