# Generated by Django 4.2.17 on 2025-01-26 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oxs', '0013_alter_repertoirevariants_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertoires',
            name='user',
            field=models.ForeignKey(default='John Doe', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='repertoirevariants',
            name='user',
            field=models.ForeignKey(default='John Doe', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
