# Generated by Django 5.1.2 on 2024-11-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oxs', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
