# Generated by Django 5.1.2 on 2024-11-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oxs', '0004_structures_alter_user_name_repertoires_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepertoriVariants',
            new_name='RepertoireVariants',
        ),
    ]
